backend:
  name: git-gateway
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "coll"
    label: "Example"
    folder: "public/example"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
    - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
